"use client";
import { CategoriaPageBase } from "../components/CategoriaPageBase";
import { EquipoTablaPosicion } from "../models/Team";

export default function Home() {
  return (
    <CategoriaPageBase
      title="Categoria C - Femenino"
      tablaZonas={tablasZonas}
      matches={[]}
      goleadores={[]}
      amarillas={[]}
    />
  );
}

const tablasZonas: EquipoTablaPosicion[][] = [
  [
    {
      pos: 1,
      equipo: "MEDICATE F.C.",
      escudo: "",
      pts: 15,
      pj: 7,
      pg: 4,
      pe: 3,
      pp: 0,
      gf: 14,
      gc: 5,
      dg: 9,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "FIASCO DA DAMA",
      escudo: "",
      pts: 13,
      pj: 7,
      pg: 4,
      pe: 1,
      pp: 2,
      gf: 11,
      gc: 7,
      dg: 4,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "INTERMIDOR FC",
      escudo: "",
      pts: 12,
      pj: 7,
      pg: 3,
      pe: 3,
      pp: 1,
      gf: 8,
      gc: 3,
      dg: 5,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "ATRA-K-LADAS",
      escudo: "",
      pts: 11,
      pj: 7,
      pg: 3,
      pe: 2,
      pp: 2,
      gf: 4,
      gc: 4,
      dg: 0,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "WINECHESTER",
      escudo: "",
      pts: 9,
      pj: 7,
      pg: 2,
      pe: 3,
      pp: 2,
      gf: 8,
      gc: 8,
      dg: 0,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "TERCER TIEMPO",
      escudo: "",
      pts: 8,
      pj: 7,
      pg: 2,
      pe: 2,
      pp: 3,
      gf: 6,
      gc: 11,
      dg: -5,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "LA PESTE BLANCA",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 7,
      gc: 10,
      dg: -3,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "REAL TORAS",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 4,
      gc: 14,
      dg: -10,
      nextMatch: "",
    },
  ],
  [
    {
      pos: 1,
      equipo: "ASTON BIRRA FC",
      escudo: "",
      pts: 19,
      pj: 7,
      pg: 6,
      pe: 1,
      pp: 0,
      gf: 20,
      gc: 3,
      dg: 17,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "CLUB DEPORTIVO NOLEGANES",
      escudo: "",
      pts: 15,
      pj: 7,
      pg: 5,
      pe: 0,
      pp: 2,
      gf: 21,
      gc: 8,
      dg: 13,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "JUGALE AL 8",
      escudo: "",
      pts: 14,
      pj: 7,
      pg: 4,
      pe: 2,
      pp: 1,
      gf: 16,
      gc: 6,
      dg: 10,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "FALSO MADRID",
      escudo: "",
      pts: 13,
      pj: 7,
      pg: 4,
      pe: 1,
      pp: 2,
      gf: 13,
      gc: 5,
      dg: 8,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "YAYO VALLECANO F.C.",
      escudo: "",
      pts: 12,
      pj: 7,
      pg: 4,
      pe: 0,
      pp: 3,
      gf: 11,
      gc: 10,
      dg: 1,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "MANDIYU'S REVENGE",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 4,
      gc: 10,
      dg: -6,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "METEPELO",
      escudo: "",
      pts: 2,
      pj: 7,
      pg: 0,
      pe: 2,
      pp: 5,
      gf: 5,
      gc: 23,
      dg: -18,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "EL PINCHA F.C.",
      escudo: "",
      pts: 1,
      pj: 7,
      pg: 0,
      pe: 1,
      pp: 6,
      gf: 3,
      gc: 28,
      dg: -25,
      nextMatch: "",
    },
  ],
  [
    {
      pos: 1,
      equipo: "WOMANCHESTER CITY",
      escudo: "",
      pts: 18,
      pj: 7,
      pg: 6,
      pe: 0,
      pp: 1,
      gf: 13,
      gc: 3,
      dg: 10,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "DETO F.C.",
      escudo: "",
      pts: 13,
      pj: 7,
      pg: 4,
      pe: 1,
      pp: 2,
      gf: 8,
      gc: 4,
      dg: 4,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "QUIERO VALE 4 F.C.",
      escudo: "",
      pts: 11,
      pj: 7,
      pg: 3,
      pe: 2,
      pp: 2,
      gf: 6,
      gc: 5,
      dg: 1,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "FLUPRINGLENSE F.C.",
      escudo: "",
      pts: 10,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 11,
      gc: 5,
      dg: 6,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "CORCHONETA",
      escudo: "",
      pts: 10,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 6,
      gc: 8,
      dg: -2,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "SINTACCTICA",
      escudo: "",
      pts: 8,
      pj: 7,
      pg: 2,
      pe: 2,
      pp: 3,
      gf: 6,
      gc: 6,
      dg: 0,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "LAS DEL BARCO",
      escudo: "",
      pts: 6,
      pj: 7,
      pg: 2,
      pe: 0,
      pp: 5,
      gf: 4,
      gc: 12,
      dg: -8,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "THE BIRDS",
      escudo: "",
      pts: 3,
      pj: 7,
      pg: 0,
      pe: 3,
      pp: 4,
      gf: 3,
      gc: 14,
      dg: -11,
      nextMatch: "",
    },
  ],
];
