# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# Build args — baked into the Next.js bundle at compile time
ARG NEXT_PUBLIC_BRAND_NAME
ARG NEXT_PUBLIC_BRAND_SUBTITLE
ARG NEXT_PUBLIC_PRIMARY_COLOR
ARG NEXT_PUBLIC_GRADIENT_COLOR
ARG NEXT_PUBLIC_LOGO_PATH
ARG NEXT_PUBLIC_LOGO_WIDTH
ARG NEXT_PUBLIC_LOGO_HEIGHT
ARG NEXT_PUBLIC_INSTAGRAM_HANDLE
ARG NEXT_PUBLIC_INSTAGRAM_URL
ARG NEXT_PUBLIC_EMAIL
ARG NEXT_PUBLIC_HERO_VIDEO_PATH
ARG NEXT_PUBLIC_HERO_BANNER_PATH
ARG NEXT_PUBLIC_CATEGORY_BANNER_PATH
ARG NEXT_PUBLIC_HOME_SLIDES
ARG NEXT_PUBLIC_SITE_TITLE
ARG NEXT_PUBLIC_COPYRIGHT_YEAR
ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_BRAND_NAME=$NEXT_PUBLIC_BRAND_NAME
ENV NEXT_PUBLIC_BRAND_SUBTITLE=$NEXT_PUBLIC_BRAND_SUBTITLE
ENV NEXT_PUBLIC_PRIMARY_COLOR=$NEXT_PUBLIC_PRIMARY_COLOR
ENV NEXT_PUBLIC_GRADIENT_COLOR=$NEXT_PUBLIC_GRADIENT_COLOR
ENV NEXT_PUBLIC_LOGO_PATH=$NEXT_PUBLIC_LOGO_PATH
ENV NEXT_PUBLIC_LOGO_WIDTH=$NEXT_PUBLIC_LOGO_WIDTH
ENV NEXT_PUBLIC_LOGO_HEIGHT=$NEXT_PUBLIC_LOGO_HEIGHT
ENV NEXT_PUBLIC_INSTAGRAM_HANDLE=$NEXT_PUBLIC_INSTAGRAM_HANDLE
ENV NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL
ENV NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL
ENV NEXT_PUBLIC_HERO_VIDEO_PATH=$NEXT_PUBLIC_HERO_VIDEO_PATH
ENV NEXT_PUBLIC_HERO_BANNER_PATH=$NEXT_PUBLIC_HERO_BANNER_PATH
ENV NEXT_PUBLIC_CATEGORY_BANNER_PATH=$NEXT_PUBLIC_CATEGORY_BANNER_PATH
ENV NEXT_PUBLIC_HOME_SLIDES=$NEXT_PUBLIC_HOME_SLIDES
ENV NEXT_PUBLIC_SITE_TITLE=$NEXT_PUBLIC_SITE_TITLE
ENV NEXT_PUBLIC_COPYRIGHT_YEAR=$NEXT_PUBLIC_COPYRIGHT_YEAR
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY . .
RUN npm run build

# Stage 2: Run standalone output
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
