"use client";
import { CategoriaPageBase } from "../components/CategoriaPageBase";
import { Match } from "../models/Match";
import { PlayerStatistic } from "../models/PlayerStatistic";
import { EquipoTablaPosicion } from "../models/Team";

export default function Home() {
  return (
    <CategoriaPageBase
      title="Categoria B - Masculino"
      tabla={data}
      matches={matches} // esto vuela, se fetchea en el componente de fixture segun id de categoria
      goleadores={goleadoresData}
      amarillas={amarillasData}
    />
  );
}

const data: EquipoTablaPosicion[] = [
  {
    pos: 1,
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    pts: 24,
    pj: 11,
    pg: 7,
    pe: 3,
    pp: 1,
    gf: 22,
    gc: 8,
    dg: +14,
    nextMatch: "https://ligacubb.com/imagenes/avesrapacesfc.png",
  },
  {
    pos: 2,
    equipo: "AVES RAPACES FC",
    escudo: "https://ligacubb.com/imagenes/avesrapacesfc.png",
    pts: 23,
    pj: 11,
    pg: 7,
    pe: 2,
    pp: 2,
    gf: 24,
    gc: 12,
    dg: +12,
    nextMatch: "https://ligacubb.com/imagenes/allblacks.png",
  },
  {
    pos: 3,
    equipo: "ALL BLACK'S",
    escudo: "https://ligacubb.com/imagenes/allblacks.png",
    pts: 23,
    pj: 11,
    pg: 7,
    pe: 2,
    pp: 2,
    gf: 13,
    gc: 5,
    dg: +8,
    nextMatch: "https://ligacubb.com/imagenes/eqvipopota.png",
  },
  {
    pos: 4,
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    pts: 21,
    pj: 11,
    pg: 6,
    pe: 3,
    pp: 2,
    gf: 22,
    gc: 14,
    dg: +8,
    nextMatch: "https://ligacubb.com/imagenes/lasmulas.png",
  },
  {
    pos: 5,
    equipo: "LAS MULAS",
    escudo: "https://ligacubb.com/imagenes/lasmulas.png",
    pts: 19,
    pj: 11,
    pg: 5,
    pe: 4,
    pp: 2,
    gf: 9,
    gc: 7,
    dg: +2,
    nextMatch: "https://ligacubb.com/imagenes/falsomadrid.png",
  },
  {
    pos: 6,
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    pts: 17,
    pj: 11,
    pg: 4,
    pe: 5,
    pp: 2,
    gf: 15,
    gc: 11,
    dg: +4,
    nextMatch: "https://ligacubb.com/imagenes/tobashuainasclub.png",
  },
  {
    pos: 7,
    equipo: "TOBAS HUAINAS CLUB",
    escudo: "https://ligacubb.com/imagenes/tobashuainasclub.png",
    pts: 16,
    pj: 11,
    pg: 5,
    pe: 1,
    pp: 5,
    gf: 22,
    gc: 15,
    dg: +7,
    nextMatch: "https://ligacubb.com/imagenes/maradonianos.png",
  },
  {
    pos: 8,
    equipo: "MARADONIANOS",
    escudo: "https://ligacubb.com/imagenes/maradonianos.png",
    pts: 15,
    pj: 11,
    pg: 3,
    pe: 6,
    pp: 2,
    gf: 9,
    gc: 10,
    dg: -1,
    nextMatch: "https://ligacubb.com/imagenes/huerginafc.png",
  },
  {
    pos: 9,
    equipo: "HUERGINA FC",
    escudo: "https://ligacubb.com/imagenes/huerginafc.png",
    pts: 12,
    pj: 11,
    pg: 3,
    pe: 3,
    pp: 5,
    gf: 10,
    gc: 12,
    dg: -2,
    nextMatch: "https://ligacubb.com/imagenes/winechester.png",
  },
  {
    pos: 10,
    equipo: "WINECHESTER",
    escudo: "https://ligacubb.com/imagenes/winechester.png",
    pts: 12,
    pj: 11,
    pg: 3,
    pe: 3,
    pp: 5,
    gf: 18,
    gc: 25,
    dg: -7,
    nextMatch: "https://ligacubb.com/imagenes/altoscanos.png",
  },
  {
    pos: 11,
    equipo: "ALTOS CAÑOS",
    escudo: "https://ligacubb.com/imagenes/altoscanos.png",
    pts: 10,
    pj: 11,
    pg: 1,
    pe: 7,
    pp: 3,
    gf: 17,
    gc: 21,
    dg: -4,
    nextMatch: "https://ligacubb.com/imagenes/moratoria.png",
  },
  {
    pos: 12,
    equipo: "MORATORIA",
    escudo: "https://ligacubb.com/imagenes/moratoria.png",
    pts: 10,
    pj: 11,
    pg: 2,
    pe: 4,
    pp: 5,
    gf: 11,
    gc: 16,
    dg: -5,
    nextMatch: "https://ligacubb.com/imagenes/mediapintafc.png",
  },
  {
    pos: 13,
    equipo: "MEDIA PINTA FC",
    escudo: "https://ligacubb.com/imagenes/mediapintafc.png",
    pts: 9,
    pj: 11,
    pg: 1,
    pe: 6,
    pp: 4,
    gf: 8,
    gc: 12,
    dg: -4,
    nextMatch: "https://ligacubb.com/imagenes/realdeportivocolombiayalem.png",
  },
  {
    pos: 14,
    equipo: "REAL DEPORTIVO COLOMBIA Y ALEM",
    escudo: "https://ligacubb.com/imagenes/realdeportivocolombiayalem.png",
    pts: 9,
    pj: 11,
    pg: 2,
    pe: 3,
    pp: 6,
    gf: 14,
    gc: 23,
    dg: -9,
    nextMatch: "https://ligacubb.com/imagenes/atraklaos.png",
  },
  {
    pos: 15,
    equipo: "ATRA-K-LAOS",
    escudo: "https://ligacubb.com/imagenes/atraklaos.png",
    pts: 7,
    pj: 11,
    pg: 1,
    pe: 4,
    pp: 6,
    gf: 8,
    gc: 21,
    dg: -13,
    nextMatch: "https://ligacubb.com/imagenes/deportivochanfle.png",
  },
  {
    pos: 16,
    equipo: "DEPORTIVO CHANFLE",
    escudo: "https://ligacubb.com/imagenes/deportivochanfle.png",
    pts: 6,
    pj: 11,
    pg: 0,
    pe: 6,
    pp: 5,
    gf: 9,
    gc: 16,
    dg: -7,
    nextMatch: "https://ligacubb.com/imagenes/cskabia.png",
  },
];

const matches: Match[] = [
  {
    team1: {
      name: "TOBAS HUAINAS CLUB",
      logoUrl: "https://ligacubb.com/imagenes/tobashuainasclub.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "EQVIPO POTA",
      logoUrl: "https://ligacubb.com/imagenes/eqvipopota.png",
      gender: "male",
      category_id: 2,
    },
    time: "14:00",
    score1: 2,
    score2: 1,
    details: [
      { type: "gol", player_name: "Montiel", team: "team1" },
      { type: "gol", player_name: "Freites", team: "team1" },
    ],
    cancha: "CANCHA 8",
    planillero: {
      name: "FALSO MADRID",
      logoUrl: "https://ligacubb.com/imagenes/falsomadrid.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "LAS MULAS",
      logoUrl: "https://ligacubb.com/imagenes/lasmulas.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "REAL DEPORTIVO COLOMBIA Y ALEM",
      logoUrl: "https://ligacubb.com/imagenes/realdeportivocolombiayalem.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "ALTOS CAÑOS",
      logoUrl: "https://ligacubb.com/imagenes/altoscanos.png",
      gender: "male",
      category_id: 2,
    },
    time: "14:00",
    score1: 4,
    score2: 4,
    details: [
      { type: "gol", player_name: "Marcelo de Lucia", team: "team1" },
      { type: "gol", player_name: "Lautaro Sica", team: "team1" },
      { type: "gol", player_name: "Francisco Fritz", team: "team1" },
      { type: "gol", player_name: "Mariano Suárez", team: "team1" },
    ],
    cancha: "CANCHA 10",
    planillero: {
      name: "MARADONIANOS",
      logoUrl: "https://ligacubb.com/imagenes/maradonianos.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "CSKA BIA",
      logoUrl: "https://ligacubb.com/imagenes/cskabia.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "MEDIA PINTA FC",
      logoUrl: "https://ligacubb.com/imagenes/mediapintafc.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "CSKA BIA",
      logoUrl: "https://ligacubb.com/imagenes/cskabia.png",
      gender: "male",
      category_id: 2,
    },
    time: "15:15",
    score1: 0,
    score2: 2,
    details: [
      { type: "gol", player_name: "Lautaro Domine Virgili", team: "team2" },
      {
        type: "gol",
        player_name: "Conrado 'El paisa' Uslenghi",
        team: "team2",
      },
    ],
    cancha: "CANCHA 8",
    planillero: {
      name: "HUERGINA FC",
      logoUrl: "https://ligacubb.com/imagenes/huerginafc.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "WINECHESTER",
      logoUrl: "https://ligacubb.com/imagenes/winechester.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "ATRA-K-LAOS",
      logoUrl: "https://ligacubb.com/imagenes/atraklaos.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "MORATORIA",
      logoUrl: "https://ligacubb.com/imagenes/moratoria.png",
      gender: "male",
      category_id: 2,
    },
    time: "15:15",
    score1: 2,
    score2: 0,
    details: [
      { type: "gol", player_name: "Mauricio Lippo", team: "team1" },
      { type: "gol", player_name: "Eugenio Cano", team: "team1" },
    ],
    cancha: "CANCHA 10",
    planillero: {
      name: "AVES RAPACES FC",
      logoUrl: "https://ligacubb.com/imagenes/avesrapacesfc.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "REAL DEPORTIVO COLOMBIA Y ALEM",
      logoUrl: "https://ligacubb.com/imagenes/realdeportivocolombiayalem.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "ALL BLACK'S",
      logoUrl: "https://ligacubb.com/imagenes/allblacks.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "FALSO MADRID",
      logoUrl: "https://ligacubb.com/imagenes/falsomadrid.png",
      gender: "male",
      category_id: 2,
    },
    time: "15:15",
    score1: 0,
    score2: 1,
    details: [],
    cancha: "CANCHA 11",
    planillero: {
      name: "ALTOS CAÑOS",
      logoUrl: "https://ligacubb.com/imagenes/altoscanos.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "EQVIPO POTA",
      logoUrl: "https://ligacubb.com/imagenes/eqvipopota.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "LAS MULAS",
      logoUrl: "https://ligacubb.com/imagenes/lasmulas.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "MARADONIANOS",
      logoUrl: "https://ligacubb.com/imagenes/maradonianos.png",
      gender: "male",
      category_id: 2,
    },
    time: "16:30",
    score1: 0,
    score2: 0,
    details: [],
    cancha: "SINTETICO 3",
    planillero: {
      name: "CSKA BIA",
      logoUrl: "https://ligacubb.com/imagenes/cskabia.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "ATRA-K-LAOS",
      logoUrl: "https://ligacubb.com/imagenes/atraklaos.png",
      gender: "male",
      category_id: 2,
    },
  },
  {
    team1: {
      name: "DEPORTIVO CHANFLE",
      logoUrl: "https://ligacubb.com/imagenes/deportivochanfle.png",
      gender: "male",
      category_id: 2,
    },
    team2: {
      name: "HUERGINA FC",
      logoUrl: "https://ligacubb.com/imagenes/huerginafc.png",
      gender: "male",
      category_id: 2,
    },
    time: "14:00",
    score1: 1,
    score2: 1,
    details: [{ type: "gol", player_name: "Matias Paolorossi", team: "team2" }],
    cancha: "CANCHA 10",
    planillero: {
      name: "MORATORIA",
      logoUrl: "https://ligacubb.com/imagenes/moratoria.png",
      gender: "male",
      category_id: 2,
    },
    linea: {
      name: "MEDIA PINTA FC",
      logoUrl: "https://ligacubb.com/imagenes/mediapintafc.png",
      gender: "male",
      category_id: 2,
    },
  },
];

const goleadoresData: PlayerStatistic[] = [
  {
    pos: 1,
    jugador: "VILLAFAÑE JUAN BAUTISTA",
    equipo: "TOBAS HUAINAS CLUB",
    escudo: "https://ligacubb.com/imagenes/tobashuainasclub.png",
    goles: 7,
  },
  {
    pos: 2,
    jugador: "BEROIZA FEDERICO OSVALDO",
    equipo: "ALTOS CAÑOS",
    escudo: "https://ligacubb.com/imagenes/altoscanos.png",
    goles: 6,
  },
  {
    pos: 3,
    jugador: "MONTIEL SANTIAGO MANUEL",
    equipo: "AVES RAPACES F.C.",
    escudo: "https://ligacubb.com/imagenes/avesrapacesfc.png",
    goles: 6,
  },
  {
    pos: 4,
    jugador: "DIAZ FACUNDO",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    goles: 5,
  },
  {
    pos: 5,
    jugador: "FERNANDEZ LY MANUEL",
    equipo: "ALL BLACK'S",
    escudo: "https://ligacubb.com/imagenes/allblacks.png",
    goles: 5,
  },
  {
    pos: 6,
    jugador: "VALENTINI SEGATORI FRANCISCO",
    equipo: "WINECHESTER",
    escudo: "https://ligacubb.com/imagenes/winechester.png",
    goles: 5,
  },
  {
    pos: 7,
    jugador: "BARCELONA JUAN AGUSTIN",
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    goles: 4,
  },
  {
    pos: 8,
    jugador: "BIGOT JUAN MARCOS",
    equipo: "ALL BLACK'S",
    escudo: "https://ligacubb.com/imagenes/allblacks.png",
    goles: 4,
  },
  {
    pos: 9,
    jugador: "DURAN MARCOS",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    goles: 4,
  },
  {
    pos: 10,
    jugador: "FERNANDEZ JUAN PABLO",
    equipo: "ALTOS CAÑOS",
    escudo: "https://ligacubb.com/imagenes/altoscanos.png",
    goles: 4,
  },
  {
    pos: 11,
    jugador: "GIRETTI AMPUERO FRANCISCO MANUEL",
    equipo: "WINECHESTER",
    escudo: "https://ligacubb.com/imagenes/winechester.png",
    goles: 4,
  },
  {
    pos: 12,
    jugador: "IOMMI LUIS JULIAN",
    equipo: "DEPORTIVO CHANFLE",
    escudo: "https://ligacubb.com/imagenes/deportivochanfle.png",
    goles: 4,
  },
  {
    pos: 13,
    jugador: "LUIS JERONIMO",
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    goles: 4,
  },
  {
    pos: 14,
    jugador: "MANGIAPANE THIAGO",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    goles: 4,
  },
  {
    pos: 15,
    jugador: "MONTIEL TOBIAS ARIEL",
    equipo: "TOBAS HUAINAS CLUB",
    escudo: "https://ligacubb.com/imagenes/tobashuainasclub.png",
    goles: 4,
  },
  {
    pos: 16,
    jugador: "MUNDORF DELRIEUX THOMAS MICHAEL",
    equipo: "REAL DEPORTIVO COLOMBIA Y ALEM",
    escudo: "https://ligacubb.com/imagenes/realdeportivocolombiayalem.png",
    goles: 4,
  },
  {
    pos: 17,
    jugador: "VIRGILI STEFANO",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    goles: 4,
  },
  {
    pos: 18,
    jugador: "AGUILAR JUAN MANUEL",
    equipo: "WINECHESTER",
    escudo: "https://ligacubb.com/imagenes/winechester.png",
    goles: 3,
  },
  {
    pos: 19,
    jugador: "ALTAFTER FRANCO MARCELO",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    goles: 3,
  },
  {
    pos: 20,
    jugador: "COPPOLA NATALIO",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    goles: 3,
  },
  {
    pos: 21,
    jugador: "DECOUD RODRIGO",
    equipo: "AVES RAPACES F.C.",
    escudo: "https://ligacubb.com/imagenes/avesrapacesfc.png",
    goles: 3,
  },
  {
    pos: 22,
    jugador: "DOMECQ GARCANDIA MAXIMILIANO MARTIN",
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    goles: 3,
  },
  {
    pos: 23,
    jugador: "DOMINE VIRGILI LAUTARO",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    goles: 3,
  },
  {
    pos: 24,
    jugador: "FARIAS MARTIN",
    equipo: "MORATORIA",
    escudo: "https://ligacubb.com/imagenes/moratoria.png",
    goles: 3,
  },
  {
    pos: 25,
    jugador: "FAVRETTO ENZO GASTON",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    goles: 3,
  },
  {
    pos: 26,
    jugador: "MARTINEZ FACUNDO",
    equipo: "AVES RAPACES F.C.",
    escudo: "https://ligacubb.com/imagenes/avesrapacesfc.png",
    goles: 3,
  },
  {
    pos: 27,
    jugador: "REYES GONZALO NICOLAS",
    equipo: "TOBAS HUAINAS CLUB",
    escudo: "https://ligacubb.com/imagenes/tobashuainasclub.png",
    goles: 3,
  },
  {
    pos: 28,
    jugador: "WEINBERDER SANTIAGO",
    equipo: "AVES RAPACES F.C.",
    escudo: "https://ligacubb.com/imagenes/avesrapacesfc.png",
    goles: 3,
  },
  {
    pos: 29,
    jugador: "ZAPATA IVAN DAMIAN",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    goles: 3,
  },
];

const amarillasData: PlayerStatistic[] = [
  {
    pos: 1,
    jugador: "ABARCA TOMAS",
    equipo: "MEDIA PINTA F.C.",
    escudo: "https://ligacubb.com/imagenes/mediapintafc.png",
    tarjetas: 4,
  },
  {
    pos: 2,
    jugador: "ADARO JONATHAN ADRIAN",
    equipo: "MARADONIANOS",
    escudo: "https://ligacubb.com/imagenes/maradonianos.png",
    tarjetas: 4,
  },
  {
    pos: 3,
    jugador: "CASTRO ALEJANDRO EZEQUIEL",
    equipo: "ALTOS CAÑOS",
    escudo: "https://ligacubb.com/imagenes/altoscanos.png",
    tarjetas: 4,
  },
  {
    pos: 4,
    jugador: "MOCHEN SPIGARDI SILVIO",
    equipo: "LAS MULAS",
    escudo: "https://ligacubb.com/imagenes/lasmulas.png",
    tarjetas: 4,
  },
  {
    pos: 5,
    jugador: "BARRETO MATIAS EZEQUIEL",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    tarjetas: 3,
  },
  {
    pos: 6,
    jugador: "BUDASSI GERMAN",
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    tarjetas: 3,
  },
  {
    pos: 7,
    jugador: "CARRASCO ANDRES",
    equipo: "HUERGINA F.C.",
    escudo: "https://ligacubb.com/imagenes/huerginafc.png",
    tarjetas: 3,
  },
  {
    pos: 8,
    jugador: "CASATTI BRAIAN RENE",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    tarjetas: 3,
  },
  {
    pos: 9,
    jugador: "COPPOLA NATALIO",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    tarjetas: 3,
  },
  {
    pos: 10,
    jugador: "DAILOFF LOPEZ AGUSTIN",
    equipo: "FALSO MADRID",
    escudo: "https://ligacubb.com/imagenes/falsomadrid.png",
    tarjetas: 3,
  },
  {
    pos: 11,
    jugador: "DURAN MARCOS",
    equipo: "CSKA BIA",
    escudo: "https://ligacubb.com/imagenes/cskabia.png",
    tarjetas: 3,
  },
  {
    pos: 12,
    jugador: "FABRE ELIAS NICOLAS",
    equipo: "MORATORIA",
    escudo: "https://ligacubb.com/imagenes/moratoria.png",
    tarjetas: 3,
  },
  {
    pos: 13,
    jugador: "GIRETTI AMPUERO FRANCISCO MANUEL",
    equipo: "WINECHESTER",
    escudo: "https://ligacubb.com/imagenes/winechester.png",
    tarjetas: 3,
  },
  {
    pos: 14,
    jugador: "IOMMI LUIS JULIAN",
    equipo: "DEPORTIVO CHANFLE",
    escudo: "https://ligacubb.com/imagenes/deportivochanfle.png",
    tarjetas: 3,
  },
  {
    pos: 15,
    jugador: "MONTENEGRO MARCOS EDUARDO",
    equipo: "ATRA-K-LAOS",
    escudo: "https://ligacubb.com/imagenes/atraklaos.png",
    tarjetas: 3,
  },
  {
    pos: 16,
    jugador: "ORTIZ AGUSTIN",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    tarjetas: 3,
  },
  {
    pos: 17,
    jugador: "PAZ VICTOR ALEXIS",
    equipo: "TOBAS HUAINAS CLUB",
    escudo: "https://ligacubb.com/imagenes/tobashuainasclub.png",
    tarjetas: 3,
  },
  {
    pos: 18,
    jugador: "SAMUEL BRUNO ALEJANDRO",
    equipo: "DEPORTIVO CHANFLE",
    escudo: "https://ligacubb.com/imagenes/deportivochanfle.png",
    tarjetas: 3,
  },
  {
    pos: 19,
    jugador: "VILLEGAS LUCAS GABRIEL",
    equipo: "EQVIPO POTA",
    escudo: "https://ligacubb.com/imagenes/eqvipopota.png",
    tarjetas: 3,
  },
];
