"use client";
import { CategoriaPageBase } from "../components/CategoriaPageBase";
import { EquipoTablaPosicion } from "../models/Team";

export default function Home() {
  return (
    <CategoriaPageBase
      title="Categoria E - Masculino"
      tablaZonas={tablasZonas}
      matches={[]}
      goleadores={[]}
      amarillas={[]}
    />
  );
}

const tablasZonas: EquipoTablaPosicion[][] = [
  [
    {
      pos: 1,
      equipo: "SANTO F.C.",
      escudo: "",
      pts: 16,
      pj: 7,
      pg: 5,
      pe: 1,
      pp: 1,
      gf: 9,
      gc: 5,
      dg: 4,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "DETO F.C.",
      escudo: "",
      pts: 15,
      pj: 7,
      pg: 4,
      pe: 3,
      pp: 0,
      gf: 15,
      gc: 3,
      dg: 12,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "SIN ANESTESIA F.C.",
      escudo: "",
      pts: 15,
      pj: 7,
      pg: 5,
      pe: 0,
      pp: 2,
      gf: 7,
      gc: 5,
      dg: 2,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "BONANZA FC",
      escudo: "",
      pts: 14,
      pj: 7,
      pg: 4,
      pe: 2,
      pp: 1,
      gf: 14,
      gc: 1,
      dg: 13,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "LUZBELITO FC",
      escudo: "",
      pts: 8,
      pj: 7,
      pg: 2,
      pe: 2,
      pp: 3,
      gf: 10,
      gc: 9,
      dg: 1,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "REAL TOROS F.C.",
      escudo: "",
      pts: 6,
      pj: 7,
      pg: 2,
      pe: 0,
      pp: 5,
      gf: 9,
      gc: 12,
      dg: -3,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "LOS YINGAS",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 10,
      gc: 18,
      dg: -8,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "YERBALENSE",
      escudo: "",
      pts: 1,
      pj: 7,
      pg: 0,
      pe: 1,
      pp: 6,
      gf: 4,
      gc: 25,
      dg: -21,
      nextMatch: "",
    },
  ],
  [
    {
      pos: 1,
      equipo: "FIASCO DA GAMA",
      escudo: "",
      pts: 19,
      pj: 7,
      pg: 6,
      pe: 1,
      pp: 0,
      gf: 20,
      gc: 3,
      dg: 17,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "CLUB ATLETICO NIUPI",
      escudo: "",
      pts: 14,
      pj: 7,
      pg: 4,
      pe: 2,
      pp: 1,
      gf: 13,
      gc: 6,
      dg: 7,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "PELUSA F.C.",
      escudo: "",
      pts: 13,
      pj: 7,
      pg: 4,
      pe: 1,
      pp: 2,
      gf: 13,
      gc: 9,
      dg: 4,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "CLUB ATLETICO LA ZONA",
      escudo: "",
      pts: 9,
      pj: 7,
      pg: 3,
      pe: 0,
      pp: 4,
      gf: 8,
      gc: 16,
      dg: -8,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "RUSTICOS FC",
      escudo: "",
      pts: 8,
      pj: 7,
      pg: 2,
      pe: 2,
      pp: 3,
      gf: 9,
      gc: 6,
      dg: 3,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "ATOMOS",
      escudo: "",
      pts: 6,
      pj: 7,
      pg: 1,
      pe: 3,
      pp: 3,
      gf: 7,
      gc: 18,
      dg: -11,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "CASCARUDO FC",
      escudo: "",
      pts: 5,
      pj: 7,
      pg: 1,
      pe: 2,
      pp: 4,
      gf: 8,
      gc: 13,
      dg: -5,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "LAMADRID FC",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 8,
      gc: 15,
      dg: -7,
      nextMatch: "",
    },
  ],
  [
    {
      pos: 1,
      equipo: "REAL SELAGOZA",
      escudo: "",
      pts: 19,
      pj: 7,
      pg: 6,
      pe: 1,
      pp: 0,
      gf: 18,
      gc: 6,
      dg: 12,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "ANKARA F.C.",
      escudo: "",
      pts: 18,
      pj: 7,
      pg: 6,
      pe: 0,
      pp: 1,
      gf: 23,
      gc: 6,
      dg: 17,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "LA TERCERA FC",
      escudo: "",
      pts: 12,
      pj: 7,
      pg: 4,
      pe: 0,
      pp: 3,
      gf: 12,
      gc: 8,
      dg: 4,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "TROTENHAM",
      escudo: "",
      pts: 10,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 13,
      gc: 11,
      dg: 2,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "SANTAS MASCULINO",
      escudo: "",
      pts: 10,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 16,
      gc: 15,
      dg: 1,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "CA WACHIPATO",
      escudo: "",
      pts: 7,
      pj: 7,
      pg: 2,
      pe: 1,
      pp: 4,
      gf: 6,
      gc: 20,
      dg: -14,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "VINESSE",
      escudo: "",
      pts: 4,
      pj: 7,
      pg: 1,
      pe: 1,
      pp: 5,
      gf: 4,
      gc: 10,
      dg: -6,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "CLUB DEPORTIVO NOLEGANES",
      escudo: "",
      pts: 1,
      pj: 7,
      pg: 0,
      pe: 1,
      pp: 6,
      gf: 3,
      gc: 19,
      dg: -16,
      nextMatch: "",
    },
  ],
  [
    {
      pos: 1,
      equipo: "REAL COHOLICOS",
      escudo: "",
      pts: 19,
      pj: 7,
      pg: 6,
      pe: 1,
      pp: 0,
      gf: 17,
      gc: 6,
      dg: 11,
      nextMatch: "",
    },
    {
      pos: 2,
      equipo: "EN LA PERISIC F.C.",
      escudo: "",
      pts: 15,
      pj: 7,
      pg: 5,
      pe: 0,
      pp: 2,
      gf: 15,
      gc: 4,
      dg: 11,
      nextMatch: "",
    },
    {
      pos: 3,
      equipo: "AMARGO Y RETRUCO",
      escudo: "",
      pts: 12,
      pj: 7,
      pg: 4,
      pe: 0,
      pp: 3,
      gf: 10,
      gc: 8,
      dg: 2,
      nextMatch: "",
    },
    {
      pos: 4,
      equipo: "DORMILONA FC",
      escudo: "",
      pts: 10,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 11,
      gc: 12,
      dg: -1,
      nextMatch: "",
    },
    {
      pos: 5,
      equipo: "THE GURIZ",
      escudo: "",
      pts: 9,
      pj: 7,
      pg: 3,
      pe: 1,
      pp: 3,
      gf: 7,
      gc: 8,
      dg: -1,
      nextMatch: "",
    },
    {
      pos: 6,
      equipo: "PICO Y PALA",
      escudo: "",
      pts: 7,
      pj: 7,
      pg: 2,
      pe: 1,
      pp: 4,
      gf: 12,
      gc: 14,
      dg: -2,
      nextMatch: "",
    },
    {
      pos: 7,
      equipo: "GUARDA LA GAMBA",
      escudo: "",
      pts: 5,
      pj: 7,
      pg: 2,
      pe: 2,
      pp: 3,
      gf: 11,
      gc: 17,
      dg: -6,
      nextMatch: "",
    },
    {
      pos: 8,
      equipo: "DOBLE MALTA",
      escudo: "",
      pts: 0,
      pj: 7,
      pg: 0,
      pe: 0,
      pp: 7,
      gf: 0,
      gc: 14,
      dg: -14,
      nextMatch: "",
    },
  ],
];
